# Generated by Django 3.0.8 on 2020-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20200725_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainfo',
            name='aid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
