# Generated by Django 3.0.8 on 2020-08-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_areainfo_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areainfo',
            name='aid',
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktest.AreaInfo'),
        ),
    ]
